CREATE DATABASE  IF NOT EXISTS `epers_ej1` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `epers_ej1`;

DROP TABLE IF EXISTS `aterrizar`;
CREATE TABLE `aterrizar` (
  `NOMBRE_USUARIO` varchar(255) NOT NULL,
  `NOMBRE` varchar(255) NOT NULL,
  `APELLIDO` varchar(255) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `Fecha` varchar(255) NOT NULL,
  `VALIDADO` tinyint(1) NOT NULL DEFAULT '0',
  `CODIGO_VALIDACION` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `CONECTADO` tinyint(1) NOT NULL DEFAULT '0',
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`,`NOMBRE_USUARIO`),
  KEY `CODIGO_VALIDACION` (`CODIGO_VALIDACION`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;
